import atom from "./atom.svg";
import star from "./star.svg";
import heart from "./heart.svg";
import starComment from "./starComment.svg";
import fb from "./fb.svg";
import ig from "./ig.svg";
import yt from "./yt.svg";
import twitter from "./twitter.svg";
import lk from "./lk.svg";
export { atom, star, heart, starComment, fb, yt, ig, lk, twitter };
